Open-Attestation/token-registry

contracts/ITitleEscrow.sol
contracts/TitleEscrow.sol
package-lock.json
scripts/postInstall.js
src/index.test.ts
test/TitleEscrow.js

Adds new function `approveNewTransferTargets` for current beneficiary to approve transfer to a beneficiary and holder. This allows the holder to execute `transferToNewEscrow` with the same beneficiary and holder (needed the two parameter to prevent front-running attacks). 
- Added new function `approveNewTransferTargets`
- Modified `transferToNewEscrow` to use the modifier `allowTransferTitleEscrow(newBeneficiary, newHolder)` to check if the the user can execute the transaction
- Refactor the nomenclatures of the entire contract to distinguish transfer to title escrow contracts (w Beneficiary & Holder) and non title escrow contracts (just Owner).

feat: approveNewTransferTargets & transferToNewEscrow to allow bene and holder to transfer independently

---

contracts/ERC721.sol

This PR changes burn address to 0xdead instead of 0x0 from the discussion:
Pros:
+ semantically correct because it is not owned by anyone anymore
+ not needing to inform consumers of a burn address
Cons:
- difficult to implement because surrendered still needs to be render-able and we can only tell this by checking the history of the token transfers
- event emission might be lost in future (they were asking people not to do event sourced state from events at devcon), and state is not immediately available to be queried
Pros:
+ easy to implement
+ known dead address are available and labeled
+ state is immediately available to be queried
Cons:
- it's a convention that needs to be propagated
- it's not possible to prove to another party that this address is uncontrolled

feat: destroyToken transfer to 0xdead

---

hardhat.config.js
package-lock.json
package.json

Currently, we are using a deprecated version of hardhat typechain. The version of typechain used is also still at v4.x. Intention is the update the version of the typechain to v5 and change out the hardhat typechain to the latest version that is currently in maintenance.
* Update Typechain from v4 to v5
* Remove deprecated Hardhat Typechain and use the latest one
* Update versions and clean up of misc dependencies

feat: upgrade typechain to v5

---

README.md

Push changes from master to beta.
* #48 
Channels: beta

chore: push changes from master to beta [no ci]

---

contracts/TitleEscrowCloneable.sol
contracts/TradetrustERC721.sol
test/TradeTrustERC721.js

In v2.x, we relied on the `deployNewTitleEscrow` and `sendToNewTitleEscrow` function to manually restore title escrows. The minter was able deploy a new title escrow with any new owners to it. In a more recent v3 update, we've refactored the function to become `restoreTitle` so that the deployment of the title escrow is automated within the function and it is easier to just make a single call to restore a title escrow. But this still allows the minter to restore to arbitrary new owners.
Since the business intention is to reject the document, it should return to the original owner in the previous title escrow. The minter should not be able to restore to any new owners he/she wants in a new title escrow. 
* Add mapping of token ID to previously surrendered title escrows
* Retrieve owner …

feat: restore to owner in previous title escrow

---

README.md

To add a new subgraph section in readme that links to the [Token Registry Subgraph](https://github.com/Open-Attestation/token-registry-subgraph) repo.
* Add subgraph section and link to token registry subgraph repo
* https://github.com/Open-Attestation/token-registry-subgraph/pull/7
* https://www.pivotaltracker.com/story/show/181397035
Channels: beta

docs: update readme with link to subgraph repo

---

contracts/TradeTrustERC721Base.sol
test/TradeTrustERC721.test.ts

The surrendered status returned false after a token has been accepted because the token ID no longer exists. This PR fixes this so that `isSurrendered` returns true for tokens that have been surrendered as well as those that have been subsequently accepted.
* Fix `isSurrendered` for accepted tokens
* Add tests coverage for `isSurrendered`
* https://github.com/Open-Attestation/token-registry-subgraph/pull/8
Channels: beta

fix: surrender status for accepted tokens

---

contracts/TradetrustERC721.sol
contracts/mocks/TradeTrustERC721Mock.sol
src/index.test.ts
test/TitleEscrowCloneable.js
test/TitleEscrowCloner.js
test/TradeTrustERC721.js
test/integration.test.js

Remove `mint` function. Minting will use `mintTitle` instead so as to restrict minting to EOA directly.
* Remove inherit from ERC721 mintable
* Update tests that rely on `mint` for testing to use a mock version of it
* https://www.pivotaltracker.com/story/show/181456297

feat: streamline mint functions

---

contracts/TradeTrustERC721.sol
contracts/access/IMinterRole.sol
contracts/access/MinterRole.sol

A general refactoring and clean-up of the code after a milestone.
* Remove overloaded `_registrySafeTransferFrom` function 
* Clean up minter role contract
* Clean up interfaces
* https://www.pivotaltracker.com/story/show/181658031
Channels: beta

refactor: clean up

---

contracts/TitleEscrow.sol

Refactor to make key methods in title escrow virtual.
* Make key methods in title escrow virtual
* Move init code into an internal method
- N.A.
Channels: beta

refactor: title escrow methods

---

.prettierrc
.solcover.js
contracts/TitleEscrowSignable.sol
contracts/interfaces/ITitleEscrowSignable.sol
contracts/lib/TitleEscrowStructs.sol
contracts/mocks/SigHelperMock.sol
contracts/utils/SigHelper.sol
src/constants/contract-interface-id.ts
src/constants/contract-interfaces.ts
test/SigHelper.test.ts
test/TitleEscrowSignable.test.ts

Adds a new variant of the title escrow with support for off-chain endorsement of beneficiary nominees. 
This variant of the title escrow will currently be an experimental feature which users can optionally opt in to use if they want. This will not be the default Title Escrow in deployment for now.
* Add `TitleEscrowSignable` contract
* Add test cases for `TitleEscrowSignable`
- https://www.pivotaltracker.com/story/show/182754734
Channels: beta

feat: signable title escrow

---

contracts/TitleEscrow.sol
contracts/TitleEscrowSignable.sol
contracts/interfaces/ITitleEscrow.sol
src/constants/contract-interfaces.ts
test/TitleEscrow.test.ts
test/TitleEscrowSignable.test.ts

Rename `beneficiaryNominee` to `nominee` for brevity and consistency.
* Rename `beneficiaryNominee` to `nominee`
* Update tests
N.A.
Channels: beta

feat: rename beneficiaryNominee to nominee

---

src/constants/contract-address.ts

The unsupported network contracts were set as zero address instead of undefined. This results in transactions being sent to `0x0` as it misses the check in the deployer when it should really have failed with an error.
This PR fixes the deployment for unsupported networks to not proceed and show the correct error message:
* Replace zero address to undefined for contract addresses
- https://github.com/Open-Attestation/open-attestation/discussions/240#discussioncomment-3680035
Channels: beta

fix: contracts zero address to undefined

---

src/constants/contract-address.ts

Fix title escrow factory error in rinkeby, ropsten and mumbai during deployment.
* Update title escrow factory addresses for rinkeby, ropsten and mumbai
N.A.
Channels: beta

fix: title escrow factory addresses

---

README.md

Remove 'ropsten' and replace with 'goerli'
* Replace 'ropsten' with 'goerli'
Deprecate all instances of rospten
ETA: Any target release date

fix: replace ropsten with goerli

---

README.md

Update the description for Quick Start in the readme that is missing Ethereum and Polygon networks.
* Update description in readme
NIL

docs: update network names in description

---

contracts/TitleEscrowFactory.sol
contracts/interfaces/TitleEscrowFactoryErrors.sol
contracts/mocks/DummyContractMock.sol
test/TitleEscrowFactory.test.ts

Add a requirement that the caller creating the title escrow must be a contract.
* Require caller to create title escrow a contract
- https://www.pivotaltracker.com/story/show/183445132

fix: title escrow factory create call

---

contracts/TitleEscrowFactory.sol
contracts/mocks/DummyContractMock.sol
contracts/mocks/TitleEscrowFactoryCallerMock.sol
test/TitleEscrowFactory.test.ts

Fix caller check for `create` in Title Escrow Factory.
* Update caller check for `create` to restrict to only contracts
- https://www.pivotaltracker.com/story/show/183445132

fix: caller for create in title escrow factory

---

README.md

The readme doc describes that the `--factory` option works with and without the `--standalone` flag. This is inaccurate after a change in #101. 
* Update the statement for `--factory` option in 
- #163  

docs(readme): update description for factory option in standalone mode

---

src/constants/contract-address.ts

This PR will change the title escrow factory address on Polygon mainnet to `0x5B5F8d94782be18E22420f3276D5ef5a1bc65C53` as requested and deployed by @isaackps (IMDA).
* Update title escrow factory address on Polygon mainnet to `0x5B5F8d94782be18E22420f3276D5ef5a1bc65C53`
- https://www.pivotaltracker.com/story/show/185858615

feat: update title escrow factory address on polygon
