Open-Attestation/token-registry

contracts/ITitleEscrow.sol, contracts/TitleEscrow.sol, package-lock.json, test/TitleEscrow.js
Reverts Open-Attestation/token-registry#3
=> Revert "Chore/refactor title escrow"

contracts/ERC721.sol, contracts/TitleEscrow.sol
This PR adds interfaceId to the tradetrusterc721 contract.
=> feat: add interfaceid to tradetrusterc721 contract

.github/pull_request_template.md
To add a simple Pull Request template for use in this repository. Intention is to have a simple template that doesn't require too much effort to write and yet sufficient for understanding the background and changes intended in a Pull Request.
* Add pull request template file
=> ci: add pull request template [skip ci]

contracts/TitleEscrowCloneable.sol
Add a surrender function in Title Escrow for convenience. Calls the function to surrender a token.
* Add `surrender()` function in Title Escrow
Channels: beta
=> feat: add surrender in title escrow

contracts/TitleEscrowCloneable.sol, contracts/mocks/TitleEscrowCloneableMock.sol, contracts/mocks/TitleEscrowClonerMock.sol, test/TitleEscrowCloneable.js, test/TitleEscrowCloner.js, test/TradeTrustERC721.js, test/integration.test.js
Hotfix for transfer in title escrow. 
Note: This currently maintains the interface for title escrow.
* Disable transferTo in title escrow
* Add surrender function
* Replace transfer implementation usage in tests with mocks
* https://www.pivotaltracker.com/story/show/180799702
=> fix: transfer issue

contracts/common/TitleEscrowCloneable.sol, contracts/interfaces/ITitleEscrow.sol, contracts/mocks/TitleEscrowCloneableMock.sol, contracts/mocks/TitleEscrowClonerMock.sol, test/TitleEscrowCloneable.js, test/TitleEscrowCloner.js, test/TradeTrustERC721.js, test/integration.test.js
Push changes from master to beta.
* All latest changes from master
Channels: beta
=> chore: push changes from master to beta

.circleci/config.yml, hardhat.config.ts
Change env name from `test` to `ci` when running in Circle CI.
* Change env name to `ci`
Channels: beta
=> chore: change env name to ci

README.md
Add audit risk disclaimer note in readme.
* Add audit risk disclaimer note in readme. 
=> docs: update readme with audit disclaimer notes

README.md
Add a notice and link to the beta branch for people who will be interested in using it. 
*  Add beta description in readme
=> docs: update readme with beta link

README.md
Update readme with beta notice message.
* Add beta notice in readme
* Add audit disclaimer notes in readme
* #68 
* #69 
Channels: beta
=> docs: update readme with beta notice

README.md
Fix broken Github issue link in readme
* Fix Github issue link in readme
* #70 
Channels: beta
=> docs: fix issue link in readme

README.md
Add a table of contents in readme file for easier navigation as the file gets larger.
* Add table of contents section in readme
Channels: beta
=> docs: add table of contents in readme

src/constants/role-hash.ts
Add admin roles to constants.
* Add admin role constants
* https://www.pivotaltracker.com/story/show/181658031
Channels: beta
=> feat: add admin role constants

hardhat.config.ts
Update solidity to 0.8.10.
* Update solc in hardhat to 0.8.10
* https://www.pivotaltracker.com/story/show/181959775
Channels: beta
=> feat: update solidity to 0.8.10

contracts/TitleEscrow.sol, contracts/TitleEscrowFactory.sol, contracts/TradeTrustERC721Base.sol, contracts/interfaces/ITitleEscrow.sol, contracts/interfaces/ITitleEscrowFactory.sol, test/TitleEscrow.test.ts, test/TitleEscrowFactory.test.ts, test/TradeTrustERC721.test.ts, test/fixtures/mint-token.fixture.ts
Move initialising owners from creating title escrow to when actually receiving the token.
* Move initialising owner to when token is received
* Update test scenarios
* https://www.pivotaltracker.com/story/show/181658031
Channels: beta
=> feat: title escrow init owners on receive token

README.md
Readme updates with changes in beta.
* Deployment usage modes
* Roles and access
* Verification for multiple networks
* Update import path in examples
* https://www.pivotaltracker.com/story/show/182112253
Channels: beta
=> docs: beta updates

README.md
Update code usage examples in readme doc.
* Update code usage examples
* https://www.pivotaltracker.com/story/show/182384110
Channels: beta
=> docs: update usage examples

package-lock.json, package.json, test/TitleEscrow.test.ts, test/fixtures/deploy-token.fixture.ts, test/index.ts
Some chore work for the tests.
* Update smock to v2.2.0
* Add `useMock` option to deploy-token fixture
N.A.
Channels: beta
=> test: chore work

hardhat.config.ts, package-lock.json, package.json, test/SigHelper.test.ts, test/TDocDeployer.test.ts, test/TitleEscrow.test.ts, test/TitleEscrowFactory.test.ts, test/TitleEscrowSignable.test.ts, test/TradeTrustERC721.test.ts, test/TradeTrustERC721Access.test.ts, test/TradeTrustERC721Impl.test.ts, test/TradeTrustERC721Pausable.test.ts, test/fixtures/deploy-escrow-factory.fixture.ts, test/fixtures/deploy-impl-deployer.fixture.ts, test/fixtures/deploy-impl-proxy.fixture.ts, test/fixtures/deploy-registry-impl.fixture.ts, test/fixtures/deploy-title-escrow.fixture.ts, test/fixtures/deploy-token.fixture.ts, test/fixtures/mint-token.fixture.ts, test/helpers/helpers.ts, test/index.ts
As more tests are added to increase the test coverage of the contracts, the test are taking more time to complete. This PR refactors the tests to improve the running speed of the tests. 
* Replace waffle with chai
* Refactor the test codes
* Bump versions of several dependencies
- https://www.pivotaltracker.com/story/show/182771265
Channels: beta
=> refactor: optimise tests

contracts/TitleEscrow.sol, contracts/TitleEscrowSignable.sol, contracts/TradeTrustERC721Base.sol, contracts/access/RegistryAccess.sol, contracts/interfaces/RegistryAccessErrors.sol, contracts/interfaces/SigHelperErrors.sol, contracts/interfaces/TDocDeployerErrors.sol, contracts/interfaces/TitleEscrowErrors.sol, contracts/interfaces/TitleEscrowSignableErrors.sol, contracts/interfaces/TradeTrustTokenErrors.sol, contracts/utils/SigHelper.sol, contracts/utils/TDocDeployer.sol, hardhat.config.ts, package-lock.json, package.json, test/SigHelper.test.ts, test/TDocDeployer.test.ts, test/TitleEscrow.test.ts, test/TitleEscrowSignable.test.ts, test/TradeTrustERC721.test.ts, test/TradeTrustERC721Impl.test.ts, test/TradeTrustERC721Pausable.test.ts
Refactor existing errors with custom errors.
* Refactor all existing errors with custom errors
* Deprecate `isSurrendered` function in token
* Update all tests
N.A.
Channels: beta
=> refactor: custom errors

README.md
Update readme with info on the methods to access the current owners.
* Update readme with info on the methods to access the current owners
N.A.
Channels: beta
=> docs: update readme with info on accessing current owners

package-lock.json, package.json
Remove an unused dep from a previous PR.
* Remove fx portal dep
N.A.
Channels: beta
=> chore: remove fx portal dep

hardhat.config.ts, src/constants/contract-address.ts
Remove support for Kovan, Rinkeby and Ropsten in config files.
* Remove support for Kovan, Rinkeby and Ropsten in config files
N.A.
Channels: beta
=> feat: remove deprecated testnets

src/constants/contract-address.ts
Update token implementation addresses.
* Update token implementation addresses for Goerli, Sepolia and Mumbai
- #132
Channels: beta
=> fix: update contract addresses

tasks/deploy-token-impl.ts
Fixes a typo in the contract path of token implementation in the deployer.
* Fix contract path of token implementation
- #132 
Channels: beta
=> fix: token impl contract path in deployer

README.md
Fix some typos with the network names in the readme docs.
* Fix typo in readme docs
NIL
Channels: beta
=> docs: fix network names

contracts/utils/TDocDeployer.sol, test/TDocDeployer.test.ts
Add `NewImplementation` event on add implementation in deployer.
* Add `NewImplementation` event in the deployer
NIL
=> fix: add implementation event

README.md
Update Readme as documentation website getting an error cos of a html tag not closing properly.
* Update readme for a html tag not closing properly.
=> fix: readme tag

src/constants/contract-address.ts
Update the testnet addresses for the title escrow factory.
* Update title escrow factory addresses for goerli, sepolia and mumbai
NiL
=> fix: title escrow factory testnet address

contracts/base/TradeTrustTokenBase.sol, contracts/base/TradeTrustTokenBaseURI.sol, test/TradeTrustTokenBaseURI.test.ts
Allow update of base URI.
* Add `setBaseURI`
- https://www.pivotaltracker.com/story/show/183445132
=> fix: add base uri

.github/workflows/linters.yml, .github/workflows/pull_requests.yml, .github/workflows/release.yml, .github/workflows/tests.yml
Refactor the CI workflow a little.
* Add new workflow for pull requests only
- #154 
- https://www.pivotaltracker.com/story/show/184233984
=> ci: refactor

hardhat.config.ts, test/SigHelper.test.ts, test/TitleEscrowSignable.test.ts, test/token/SBTUpgradeable.test.ts
Quick fix for are some typing issues during build when installed with some of the newer dep versions. 
* Minor fixes in hardhat config and tests
=> fix: build issues with newer dep versions

contracts/TitleEscrow.sol, contracts/TitleEscrowFactory.sol, contracts/TradeTrustToken.sol, contracts/base/RegistryAccess.sol, contracts/base/SBTUpgradeable.sol, contracts/base/TradeTrustSBT.sol, contracts/base/TradeTrustTokenBase.sol, contracts/base/TradeTrustTokenBaseURI.sol, contracts/base/TradeTrustTokenBurnable.sol, contracts/base/TradeTrustTokenMintable.sol, contracts/base/TradeTrustTokenRestorable.sol, contracts/interfaces/ITitleEscrow.sol, contracts/interfaces/ITitleEscrowFactory.sol, contracts/interfaces/ITitleEscrowSignable.sol, contracts/interfaces/ITradeTrustSBT.sol, contracts/interfaces/ITradeTrustTokenBurnable.sol, contracts/interfaces/ITradeTrustTokenMintable.sol, contracts/interfaces/ITradeTrustTokenRestorable.sol, contracts/presets/TitleEscrowSignable.sol, contracts/presets/TradeTrustTokenStandard.sol, contracts/utils/TDocDeployer.sol
This PR adds natspec comments to the contracts.
* Add natspec comments
- https://www.pivotaltracker.com/story/show/185343609
=> docs: add natspec comments

README.md, hardhat.config.ts, src/constants/contract-address.ts
Remove Goerli network.
* Remove Goerli network
- https://www.pivotaltracker.com/story/show/186138607
=> feat: remove goerli network
